version: 2

updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      python-dependencies-patch-minor:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
      python-dependencies-major:
        patterns:
          - "*"
        update-types:
          - "major"
    commit-message:
      prefix: "build(deps)"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions-patch-minor:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
      github-actions-major:
        patterns:
          - "*"
        update-types:
          - "major"
    commit-message:
      prefix: "ci(deps)"
